package io.github.sidyn4444.webhooks.worker.persistence;

import io.github.sidyn4444.webhooks.common.model.DeliveryJob;
import io.github.sidyn4444.webhooks.worker.delivery.DeliveryResult;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.Instant;

/**
 * One row in the delivery log: a permanent record of a single delivery attempt.
 *
 * <p>Everything the worker has produced so far exists only as a log line, which answers "what is
 * happening now" and nothing else. Once the log rotates, "what happened to event X last Tuesday?"
 * has no answer at all. This class is what makes that question answerable — and in Week 6 it is
 * the raw material for the throughput, error-rate and p95-latency panels.
 *
 * <p>Written once per attempt, success or failure, and never updated. An append-only record of
 * things that happened; a delivery that has already occurred cannot stop having occurred.
 *
 * <h2>🔴 The design decision: there is no payload column</h2>
 *
 * <p>The payload lives in Redis, because the worker genuinely cannot deliver a webhook without it.
 * It is deliberately absent here, and the reasoning matters more than the omission.
 *
 * <p>The tempting justification is "nobody looks at the Redis queue." That is the weak version and
 * it does not survive a follow-up question — Redis holds exactly the same bytes. The real argument
 * is <b>need versus exposure</b>, applied per store:
 *
 * <ul>
 *   <li><b>The queue</b> needs the payload (it cannot deliver without it), and is transient,
 *       internal, and password-protected inside a private network. Real need, small exposure.</li>
 *   <li><b>This table</b> does not need it — "event X returned 500 in 42ms" is a complete record
 *       without a single byte of the payload — and it is permanent, queryable by anyone with
 *       database access, backed up, and the thing that gets screenshotted into a public README.
 *       No need, large exposure.</li>
 * </ul>
 *
 * <p>So the payload is stripped exactly where it is not required. The principle has a name —
 * <b>data minimization</b> — and the test generalises: <i>does this store require the field to do
 * its job, and how exposed is this store?</i> A payload may contain an email address, a phone
 * number, or an order total; none of that belongs in a permanent audit table that exists to answer
 * questions about timing and status.
 *
 * <p>Note also what this table cannot leak by construction rather than by policy: with no column
 * to write to, no future code path can accidentally start persisting payloads here. A schema is a
 * stronger control than a code review.
 *
 * <h2>Why a class and not a record</h2>
 *
 * <p>{@code Event} and {@code DeliveryJob} are both {@code record}s — immutable, compact, ideal for
 * data crossing a boundary. JPA cannot use one. It requires a no-argument constructor and the
 * ability to set fields on an object it constructed itself, because loading a row means creating a
 * blank instance and filling it in. A record is final and has no such constructor.
 *
 * <p>This is not a shortcoming so much as a difference in what the two things are: a record models
 * a value, and an entity models <i>a row that the persistence layer owns and manages</i>.
 */
@Entity
@Table(name = "delivery_attempts")
public class DeliveryAttempt {

    /**
     * The primary key, generated by the database.
     *
     * <p>{@code GenerationType.IDENTITY} maps to a Postgres identity column: the database assigns
     * the number on insert. The alternative, {@code SEQUENCE}, pre-fetches blocks of ids so
     * Hibernate can batch many inserts into one round trip.
     *
     * <p>{@code IDENTITY} is chosen because it is simpler and the batching advantage is worth
     * nothing here — the poll loop writes exactly one row per delivery, one at a time, so there is
     * never a batch to combine. The decision would flip immediately for bulk imports or any path
     * inserting hundreds of rows at once, where {@code SEQUENCE} is meaningfully faster.
     *
     * <p>{@code Long} rather than {@code long} deliberately: before the row is saved there is no
     * id, and {@code null} says that honestly where {@code 0} would be a lie.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The caller's idempotency key, carried unchanged from the original event.
     *
     * <p>This is the column every real query starts from — "what happened to event X?" — so it is
     * indexed in the migration (10c). Not unique: one event legitimately produces several rows,
     * one per attempt, which is the entire point of an attempt log.
     */
    @Column(name = "event_id", nullable = false, length = 36)
    private String eventId;

    /** Which try this was: 1 for the first, up to the retry ceiling carried on the job. */
    @Column(name = "attempt_number", nullable = false)
    private int attemptNumber;

    /**
     * 🔴 NULLABLE, and this is the most important column definition in the file.
     *
     * <p>Three things can happen on an attempt: a success status, an error status, or <b>no
     * response at all</b> — a timeout, a DNS failure, a refused connection. In that third case no
     * status code exists, and the column has to be able to say so.
     *
     * <p>The alternative is inventing a value, and the tempting one is {@code 500}. That is an
     * active lie: {@code 500} means <i>the subscriber's server told us it failed</i>, while a
     * timeout means <i>we never heard from them</i>. Different cause, different owner, different
     * fix — one is a bug on their side, the other may be DNS, a firewall, or our own network.
     * Someone debugging from a table full of fabricated 500s investigates the wrong system
     * entirely, and nothing in the data hints that they should look elsewhere.
     *
     * <p>This is the same reasoning that made {@link DeliveryResult#statusCode()} an
     * {@code Integer} rather than an {@code int} in 9c, now carried through to the schema. A
     * nullable column is the database's way of saying "this genuinely may not exist."
     */
    @Column(name = "status_code")
    private Integer statusCode;

    /**
     * Whether the attempt counts as delivered.
     *
     * <p>Strictly this is derivable — success means a 2xx — so storing it is denormalization, and
     * the honest cost is that a bug could write a row where the flag and the status disagree.
     *
     * <p>It earns its place for two reasons. Every dashboard and alert asks "how many failed?",
     * and without this column each of those queries has to re-encode the 2xx rule; the definition
     * would then live in a dozen places instead of one. More sharply: a null status code makes
     * naive SQL wrong in a way nobody notices, because {@code status_code NOT BETWEEN 200 AND 299}
     * silently excludes NULL rows — so the timeouts, the worst failures in the system, vanish from
     * the failure count.
     *
     * <p>The single definition lives in {@link DeliveryResult#succeeded()} and is copied here at
     * write time, so the flag and the status code can never be derived by different rules.
     */
    @Column(name = "success", nullable = false)
    private boolean success;

    /**
     * How long the attempt took, including one that ran to the timeout.
     *
     * <p>Often the most diagnostic number in the row: a failure at 10,003ms is a timeout, a failure
     * at 12ms is a connection refused instantly. Identical outcome, completely different
     * investigation. In Week 6 this column becomes the p50/p95/p99 latency panels.
     */
    @Column(name = "duration_ms", nullable = false)
    private long durationMs;

    /**
     * Short description of a transport failure, or null when a response arrived.
     *
     * <p>Not in the original 2b sketch, added because 9c produces it and a row with a null status
     * code says nothing about <i>why</i> without it. "timeout after 10000ms" and
     * "ConnectException: connection refused" are the same shape of failure and completely
     * different problems.
     *
     * <p>Deliberately a short, stable description rather than the raw exception message, which is
     * long, deeply nested and changes between library versions — poor material for something that
     * will be grouped in a dashboard. It also must never contain payload content; it describes the
     * transport, not the message.
     */
    @Column(name = "failure_reason", length = 255)
    private String failureReason;

    /**
     * When the attempt happened, in UTC.
     *
     * <p>{@code Instant} maps to {@code timestamp with time zone}, which stores an unambiguous
     * moment. A naive local timestamp would be unreadable across regions and would silently break
     * ordering when the servers writing it sit in different zones — and in Week 5 they will.
     *
     * <p>Wall-clock time is correct <i>here</i>, unlike the duration measurement in 9c which needs
     * a monotonic clock: this records when something happened, which is exactly what wall-clock
     * time is for.
     */
    @Column(name = "attempted_at", nullable = false)
    private Instant attemptedAt;

    /**
     * Required by JPA, used by nobody else.
     *
     * <p>Loading a row means constructing a blank object and filling in its fields, so the
     * persistence provider needs a constructor that takes nothing. {@code protected} rather than
     * {@code public} because it exists for the framework: it leaves an object with every field
     * unset, which is never a valid state for application code to create.
     */
    protected DeliveryAttempt() {
    }

    private DeliveryAttempt(String eventId, int attemptNumber, Integer statusCode, boolean success,
                            long durationMs, String failureReason, Instant attemptedAt) {
        this.eventId = eventId;
        this.attemptNumber = attemptNumber;
        this.statusCode = statusCode;
        this.success = success;
        this.durationMs = durationMs;
        this.failureReason = failureReason;
        this.attemptedAt = attemptedAt;
    }

    /**
     * Builds the record of one attempt from the job and its outcome.
     *
     * <p>The mapping lives in one place on purpose. Constructing rows at the call site means every
     * future caller re-decides what "success" means and which fields to copy, and the first one to
     * get it slightly wrong produces a log that quietly disagrees with itself.
     *
     * <p>🔴 Note what is NOT copied: {@code job.payload()}. There is no column for it, so this is
     * enforced by the schema rather than by remembering — the strongest form of the rule.
     *
     * @param job    the delivery job, for the event id and attempt number
     * @param result the outcome produced by the sender (9c)
     */
    public static DeliveryAttempt of(DeliveryJob job, DeliveryResult result) {
        return new DeliveryAttempt(
                job.eventId(),
                job.attemptNumber(),
                result.statusCode(),        // null when nothing came back — recorded as null
                result.succeeded(),         // the one definition of success, from 9c
                result.durationMs(),
                result.failureReason(),
                Instant.now());
    }

    public Long getId() {
        return id;
    }

    public String getEventId() {
        return eventId;
    }

    public int getAttemptNumber() {
        return attemptNumber;
    }

    public Integer getStatusCode() {
        return statusCode;
    }

    public boolean isSuccess() {
        return success;
    }

    public long getDurationMs() {
        return durationMs;
    }

    public String getFailureReason() {
        return failureReason;
    }

    public Instant getAttemptedAt() {
        return attemptedAt;
    }

    /**
     * Deliberately excludes every field that could carry personal data — which, given there is no
     * payload column, means it is safe by construction. Included because an entity with no
     * {@code toString} eventually gets logged as {@code DeliveryAttempt@4f2b1a}, and someone then
     * "fixes" that by logging the whole object.
     */
    @Override
    public String toString() {
        return "DeliveryAttempt{id=" + id
                + ", eventId=" + eventId
                + ", attempt=" + attemptNumber
                + ", status=" + statusCode
                + ", success=" + success
                + ", durationMs=" + durationMs + '}';
    }
}
