-- =============================================================================
--  V1 — the delivery log.
--
--  One row per delivery attempt, success or failure. Append-only: a delivery that
--  has already happened cannot stop having happened, so nothing here is ever updated.
--
--  🔴 THIS FILE IS IMMUTABLE ONCE IT HAS RUN ANYWHERE.
--  Flyway stores a checksum of these bytes in flyway_schema_history. Editing the file
--  after it has been applied fails the next startup with "Migration checksum mismatch"
--  — Flyway is saying the file it ran is no longer the file on disk, so it can no
--  longer reason about the state of the database. Schema changes go in V2, V3, …
--
--  Naming: V<version>__<description>.sql — TWO underscores between version and
--  description. One underscore and Flyway does not recognise it as a migration at all,
--  silently, which is a memorable half hour to lose.
--
--  Must stay in agreement with DeliveryAttempt.java: from this point on
--  spring.jpa.hibernate.ddl-auto=validate compares the two at every startup and
--  refuses to boot if they disagree. Two independent definitions, one enforced match.
-- =============================================================================

CREATE TABLE delivery_attempts (

    -- Assigned by the database, never by application code — two workers inventing
    -- ids concurrently would eventually pick the same number.
    -- GENERATED BY DEFAULT AS IDENTITY is what @GeneratedValue(strategy = IDENTITY) maps to.
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- The caller's idempotency key, carried unchanged from the original event.
    -- NOT unique on purpose: one event legitimately produces several rows, one per
    -- attempt, which is the entire thing this table exists to record.
    event_id            VARCHAR(36)  NOT NULL,

    -- Which try this was. 1 for the first, up to the retry ceiling carried on the job.
    attempt_number      INTEGER      NOT NULL,

    -- 🔴 NULLABLE, DELIBERATELY — the most important line in this file.
    --
    -- Three things can happen on an attempt: a success status, an error status, or
    -- NO RESPONSE AT ALL (timeout, DNS failure, refused connection). In that third
    -- case no status code exists, and the column has to be able to say so.
    --
    -- The tempting alternative is writing 500. That is an active lie: 500 means the
    -- subscriber's server TOLD us it failed, while a timeout means we never heard from
    -- them. Different cause, different owner, different fix — one is a bug on their
    -- side, the other may be DNS, a firewall, or our own network. Anyone debugging from
    -- a table full of fabricated 500s investigates the wrong system, with nothing in the
    -- data to suggest otherwise.
    status_code         INTEGER,

    -- Derivable from status_code (success = any 2xx), and stored anyway.
    --
    -- Not laziness — it is the fix for a silent SQL trap. The obvious failure query,
    -- "status_code NOT BETWEEN 200 AND 299", excludes NULL rows, because a comparison
    -- against NULL is neither true nor false. So every timeout — the worst failures in
    -- the system — vanishes from the failure count, with no error and no reason for
    -- anyone to doubt the number. Storing the boolean makes the obvious query correct.
    success             BOOLEAN      NOT NULL,

    -- Often the most diagnostic number in the row: a failure at 10,003ms is a timeout,
    -- a failure at 12ms is a connection refused instantly. Identical outcome, completely
    -- different investigation. Becomes the p50/p95/p99 panels in Week 6.
    duration_ms         BIGINT       NOT NULL,

    -- Short, stable description of a transport failure; NULL when a response arrived.
    -- Without it a NULL status_code says nothing about WHY, and "timeout after 10000ms"
    -- versus "connection refused" are completely different problems.
    failure_reason      VARCHAR(255),

    -- WITH TIME ZONE, not a naive local timestamp. Ordering must survive workers running
    -- in different regions, which they will from Week 5. Wall-clock time is correct here
    -- because this records WHEN something happened; durations use a monotonic clock.
    attempted_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

-- =============================================================================
--  🔴 THERE IS NO payload COLUMN, AND ITS ABSENCE IS THE DESIGN.
--
--  The payload lives in Redis because the worker cannot deliver a webhook without it.
--  It is deliberately absent here, and the reasoning is need versus exposure, per store:
--
--    the queue  — NEEDS the payload (cannot deliver without it), and is transient,
--                 internal, password-protected. Real need, small exposure.  → keep
--    this table — does NOT need it ("event X returned 500 in 42ms" is a complete
--                 record), and is permanent, queryable, backed up, replicated, and
--                 screenshotted into a public README. No need, large exposure. → strip
--
--  The weak version of this argument is "nobody looks at the Redis queue" — it does not
--  survive a follow-up, because Redis holds the identical bytes. The real reason is that
--  one store requires the field to do its job and the other does not.
--
--  And the absence is structural rather than a policy: with no column to write to, no
--  future code path can start persisting payloads here — not through a debugging change,
--  not through a refactor. A schema is a stronger control than a code review, because it
--  does not depend on anyone remembering.
-- =============================================================================

-- Every real query starts from the event id — "what happened to event X?" — and without
-- an index that is a full table scan of a table designed to grow forever. Cheap to add
-- now, disruptive to add later on a large table.
--
-- Hibernate's schema validation ignores indexes entirely, so this exists purely for the
-- database's benefit and cannot cause a validate mismatch.
CREATE INDEX idx_delivery_attempts_event_id ON delivery_attempts (event_id);
